# Generated by Django 3.2.5 on 2021-07-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptdetailed',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
