# Generated by Django 3.2.5 on 2021-07-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptdetailed',
            name='image',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
