# Generated by Django 3.2.5 on 2021-07-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0005_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
    ]
