# Generated by Django 3.2.5 on 2021-07-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0008_auto_20210726_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='receipt.RecipeIngredient'),
        ),
    ]
