# Generated by Django 3.2.5 on 2021-07-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0010_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=False),
        ),
    ]
